/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/studio-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Studio opening and registration synchronization */
        get: operations["getAdminStudioStatus"];
        /** Open or pause registration and booking */
        put: operations["updateStudioStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studio-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public studio opening status */
        get: operations["getStudioStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the published studio team */
        get: operations["getStudioTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read studio team content for administration */
        get: operations["adminGetStudioTeam"];
        /** Update the studio team section */
        put: operations["adminUpdateStudioTeam"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/studio-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a portrait or studio team image */
        post: operations["adminUploadStudioImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency readiness check */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an opaque application session
         * @description Server-to-server only. Requires a time-bound HMAC signature derived from SESSION_SECRET; it is not a browser API.
         */
        post: operations["createInternalApplicationSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/sessions/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve and revalidate an opaque application session
         * @description Server-to-server only. Revalidates Keycloak identity and roles at least every 15 minutes.
         */
        post: operations["resolveInternalApplicationSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke an opaque application session
         * @description Server-to-server only. Clears the encrypted refresh token and requests refresh-token revocation from Keycloak.
         */
        post: operations["revokeInternalApplicationSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/class-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active class types */
        get: operations["listClassTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/class-types/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public class type detail and upcoming sessions */
        get: operations["getClassType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approved public reviews */
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published Studio Balance news */
        get: operations["listNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transformations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approved client transformations */
        get: operations["listTransformations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an image used by published content or an active instructor */
        get: operations["getPublicMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public class sessions */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a public class session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated client profile */
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated client profile */
        patch: operations["updateCurrentAccount"];
        trace?: never;
    };
    "/api/v1/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated client's account notifications */
        get: operations["listMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated client's favorite class types */
        get: operations["listMyFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/favorites/{classTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an active class type to favorites */
        post: operations["addMyFavorite"];
        /** Remove a class type from favorites */
        delete: operations["removeMyFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an idempotent booking */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated client's bookings */
        get: operations["listMyBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bookings/{bookingId}/cancellation-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview the consequence of cancelling a booking */
        get: operations["previewBookingCancellation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bookings/{bookingId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a client booking */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the operational dashboard */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/class-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all class types for administration */
        get: operations["adminListClassTypes"];
        put?: never;
        /** Create a class type */
        post: operations["adminCreateClassType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/class-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a class type */
        patch: operations["adminUpdateClassType"];
        trace?: never;
    };
    "/api/v1/admin/instructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instructors for administration */
        get: operations["adminListInstructors"];
        put?: never;
        /** Create an instructor */
        post: operations["adminCreateInstructor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/instructors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an instructor */
        patch: operations["adminUpdateInstructor"];
        trace?: never;
    };
    "/api/v1/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions including operational fields */
        get: operations["adminListSessions"];
        put?: never;
        /** Create a one-off session */
        post: operations["adminCreateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a scheduled session */
        patch: operations["adminUpdateSession"];
        trace?: never;
    };
    "/api/v1/admin/sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a session and all active bookings without fees */
        post: operations["adminCancelSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews including drafts */
        get: operations["adminListReviews"];
        put?: never;
        /** Create a review draft or approved review */
        post: operations["adminCreateReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update, publish, feature or hide a review */
        patch: operations["adminUpdateReview"];
        trace?: never;
    };
    "/api/v1/admin/content/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List news including drafts */
        get: operations["adminListNews"];
        put?: never;
        /** Create a news draft or published item */
        post: operations["adminCreateNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update, publish, feature or hide news */
        patch: operations["adminUpdateNews"];
        trace?: never;
    };
    "/api/v1/admin/content/transformations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transformations including drafts */
        get: operations["adminListTransformations"];
        put?: never;
        /** Create a transformation */
        post: operations["adminCreateTransformation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/transformations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update, publish, feature or hide a transformation */
        patch: operations["adminUpdateTransformation"];
        trace?: never;
    };
    "/api/v1/admin/media/transformation-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and normalize a transformation image */
        post: operations["adminUploadTransformationImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an uploaded image in administration */
        get: operations["adminGetMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List client profiles */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings for operations */
        get: operations["adminListBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record attendance or no-show */
        post: operations["adminRecordAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminStudioStatus: {
            open: boolean;
            announcement: string | null;
            requestedOpen: boolean;
            registrationSynced: boolean;
        };
        StudioStatus: {
            open: boolean;
            announcement: string | null;
        };
        StudioImage: {
            src: string;
            alt: string;
            width: number;
            height: number;
        };
        InstructorClassAssignment: {
            /** Format: uuid */
            classTypeId: string;
            scheduleNote: string;
        };
        ClassInstructor: {
            /** Format: uuid */
            id: string;
            displayName: string;
            portrait: components["schemas"]["StudioImage"] | null;
            bio: string;
            scheduleNote: string;
        };
        TeamContent: {
            title: string;
            body: string;
            photo: components["schemas"]["StudioImage"] | null;
        };
        AdminTeamInput: {
            title: string;
            body: string;
            photoAlt: string;
            published: boolean;
            /**
             * Format: uuid
             * @description Omit to preserve the photo; null removes it including the bundled preview.
             */
            photoAssetId?: string | null;
        };
        AdminTeam: {
            title: string;
            body: string;
            photoAlt: string;
            published: boolean;
            /**
             * Format: uuid
             * @description Omit to preserve the photo; null removes it including the bundled preview.
             */
            photoAssetId: string | null;
            photo: components["schemas"]["StudioImage"] | null;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
            version: string;
            /** Format: date-time */
            timestamp: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                }[];
                requestId: string;
            };
        };
        /** @enum {string} */
        InternalSessionKind: "web" | "admin";
        InternalSessionIdentity: {
            subject: string;
            /** Format: email */
            email: string;
            emailVerified: boolean;
            firstName?: string;
            lastName?: string;
            /** @description True only when the original interactive authentication included the OTP method in the signed AMR claim. */
            mfaVerified: boolean;
            roles: ("client" | "admin" | "super_admin")[];
        };
        InternalSessionCreateRequest: {
            kind: components["schemas"]["InternalSessionKind"];
            refreshToken: string;
            session: components["schemas"]["InternalSessionIdentity"];
        };
        InternalSessionTokenRequest: {
            kind: components["schemas"]["InternalSessionKind"];
            token: string;
        };
        InternalSessionCreated: {
            token: string;
        };
        InternalSessionResolved: {
            session: components["schemas"]["InternalSessionIdentity"] | null;
        };
        Money: {
            amount: string;
            /** @constant */
            currency: "CZK";
        };
        ClassTypeSummary: {
            name: string;
            slug: string;
            tagline: string;
        };
        ClassType: components["schemas"]["ClassTypeSummary"] & {
            /** Format: uuid */
            id: string;
            description: string;
            durationMinutes: number;
            arrivalLeadMinutes: number;
            difficulty: number;
            benefits: string;
            audience: string;
            suitableForBeginners: boolean;
            defaultEquipment: string;
            whatToBring: string;
            practicalNotice: string;
            heroImage: components["schemas"]["MediaImage"] | null;
            seoTitle: string;
            seoDescription: string;
        };
        MediaImage: {
            src: string;
            alt: string;
        };
        ClassTypeDetail: {
            name: string;
            slug: string;
            tagline: string;
            /** Format: uuid */
            id: string;
            description: string;
            durationMinutes: number;
            arrivalLeadMinutes: number;
            difficulty: number;
            benefits: string;
            audience: string;
            suitableForBeginners: boolean;
            defaultEquipment: string;
            whatToBring: string;
            practicalNotice: string;
            heroImage: components["schemas"]["MediaImage"] | null;
            seoTitle: string;
            seoDescription: string;
            upcomingSessions: components["schemas"]["PublicSession"][];
            instructors: components["schemas"]["ClassInstructor"][];
        };
        InstructorSummary: {
            /** Format: uuid */
            id: string;
            displayName: string;
            portrait: components["schemas"]["StudioImage"] | null;
        };
        Location: {
            name: string;
            address: string;
        };
        PublicSession: {
            /** Format: uuid */
            id: string;
            classType: components["schemas"]["ClassTypeSummary"];
            instructor: components["schemas"]["InstructorSummary"];
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            /** @constant */
            timezone: "Europe/Prague";
            /** Format: date-time */
            arrivalAt: string;
            /** @enum {string} */
            availability: "bookable" | "full" | "closed" | "cancelled" | "completed";
            price: components["schemas"]["Money"];
            location: components["schemas"]["Location"];
            equipment: string;
            suitability: string;
            whatToBring: string;
            changeNotice?: string | null;
        };
        MeResponse: {
            subject: string;
            /** Format: email */
            email: string;
            emailVerified: boolean;
            roles: ("client" | "admin" | "super_admin")[];
            firstName: string | null;
            lastName: string | null;
            phone: string | null;
            termsVersion: string | null;
            profileComplete: boolean;
        };
        AccountNotification: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "booking_confirmed" | "booking_cancelled" | "lesson_reminder" | "session_changed" | "session_cancelled";
            title: string;
            body: string;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        FavoriteClassType: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            tagline: string;
            difficulty: number;
            heroImage: components["schemas"]["MediaImage"] | null;
            /** Format: date-time */
            favoritedAt: string;
        };
        NewsItem: {
            /** Format: uuid */
            id: string;
            title: string;
            summary: string;
            body: string;
            /** Format: date-time */
            publishedAt: string;
        };
        AdminNewsInput: {
            title: string;
            summary: string;
            body: string;
            published: boolean;
            featured: boolean;
            /** Format: date-time */
            publishedAt: string | null;
            sortOrder: number;
        };
        AdminNewsItem: {
            /** Format: uuid */
            id: string;
            title: string;
            summary: string;
            body: string;
            published: boolean;
            featured: boolean;
            /** Format: date-time */
            publishedAt: string | null;
            sortOrder: number;
        };
        UpdateMeRequest: {
            firstName: string;
            lastName: string;
            phone: string;
        };
        CreateBookingRequest: {
            /** Format: uuid */
            sessionId: string;
            /** @constant */
            termsVersion: "2026-08-04";
            /** @constant */
            termsAccepted: true;
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "reserved" | "cancelled_on_time" | "cancelled_late" | "attended" | "no_show" | "cancelled_by_studio";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            cancellationCutoffAt: string;
            fee: components["schemas"]["Money"] | null;
            session: components["schemas"]["PublicSession"];
        };
        CancellationPreview: {
            /** @enum {string} */
            mode: "on_time" | "late" | "free_change_window";
            /** Format: date-time */
            cutoffAt: string;
            fee: components["schemas"]["Money"] | null;
            /** @constant */
            paymentMethod: "at_studio";
        };
        CancelBookingRequest: {
            lateCancellationConfirmed: boolean;
        };
        Review: {
            /** Format: uuid */
            id: string;
            authorLabel: string;
            body: string;
            source: string | null;
            /** Format: date */
            reviewedOn: string | null;
            rating: number | null;
            classType: {
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
            } | null;
        };
        AdminReviewInput: {
            authorLabel: string;
            body: string;
            source?: string | null;
            /** Format: date */
            reviewedOn: string | null;
            rating: number | null;
            classTypeId: string | null;
            /** @description Must be true before publication. */
            consentConfirmed: boolean;
            published: boolean;
            featured: boolean;
            sortOrder: number;
        };
        AdminReview: {
            /** Format: uuid */
            id: string;
            authorLabel: string;
            body: string;
            source: string | null;
            /** Format: date */
            reviewedOn: string | null;
            rating: number | null;
            classType: {
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
            } | null;
            classTypeId: string | null;
            consentConfirmed: boolean;
            published: boolean;
            featured: boolean;
            sortOrder: number;
        };
        TransformationImage: {
            url: string;
            width: number;
            height: number;
        };
        Transformation: {
            /** Format: uuid */
            id: string;
            title: string;
            story: string;
            attribution: string;
            beforeImage: components["schemas"]["TransformationImage"];
            afterImage: components["schemas"]["TransformationImage"];
            classType: {
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
            } | null;
        };
        AdminTransformationInput: {
            title: string;
            story: string;
            attribution: string;
            /** Format: uuid */
            beforeAssetId: string;
            /** Format: uuid */
            afterAssetId: string;
            classTypeId: string | null;
            /** @description Must be true before publication. */
            consentConfirmed: boolean;
            published: boolean;
            /** @description May be true only for published content. */
            featured: boolean;
            sortOrder: number;
        };
        AdminTransformation: {
            /** Format: uuid */
            id: string;
            title: string;
            story: string;
            attribution: string;
            beforeImage: components["schemas"]["TransformationImage"];
            afterImage: components["schemas"]["TransformationImage"];
            classType: {
                /** Format: uuid */
                id: string;
                name: string;
                slug: string;
            } | null;
            /** Format: uuid */
            beforeAssetId: string;
            /** Format: uuid */
            afterAssetId: string;
            classTypeId: string | null;
            consentConfirmed: boolean;
            published: boolean;
            featured: boolean;
            sortOrder: number;
        };
        MediaUploadResponse: {
            /** Format: uuid */
            id: string;
            url: string;
            width: number;
            height: number;
        };
        AdminDashboardSession: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            startAt: string;
            /** @enum {string} */
            status: "scheduled" | "cancelled" | "completed";
            capacity: number;
            bookingCount: number;
            className: string;
            instructorName: string;
        };
        AdminDashboardMetrics: {
            reservationsThisWeek: number;
            attendedThisMonth: number;
            noShowsThisMonth: number;
            lateCancellationsThisMonth: number;
            attendanceRate90Days: number | null;
            /** @description Sum of snapshotted prices for bookings marked attended. This is an operational estimate, not accounting revenue or proof of payment. */
            estimatedAttendedValueThisMonthCents: number;
        };
        AdminClassPopularity: {
            /** Format: uuid */
            classTypeId: string;
            className: string;
            reservations: number;
            attended: number;
        };
        AdminWeeklyAttendance: {
            /** Format: date */
            weekStart: string;
            attended: number;
        };
        AdminDashboard: {
            activeBookings: number;
            clients: number;
            today: components["schemas"]["AdminDashboardSession"][];
            nextWeek: components["schemas"]["AdminDashboardSession"][];
            metrics: components["schemas"]["AdminDashboardMetrics"];
            classPopularity: components["schemas"]["AdminClassPopularity"][];
            weeklyAttendance: components["schemas"]["AdminWeeklyAttendance"][];
        };
        AdminMutationResponse: {
            /** Format: uuid */
            id: string;
        };
        AdminClassTypeInput: {
            slug: string;
            name: string;
            tagline: string;
            description: string;
            durationMinutes: number;
            arrivalLeadMinutes: number;
            active: boolean;
            sortOrder: number;
            difficulty: number;
            benefits: string;
            audience: string;
            suitableForBeginners: boolean;
            defaultEquipment: string;
            whatToBring: string;
            practicalNotice: string;
            heroImagePath: string;
            heroImageAlt: string;
            seoTitle: string;
            seoDescription: string;
        };
        AdminClassType: components["schemas"]["AdminClassTypeInput"] & {
            /** Format: uuid */
            id: string;
        };
        AdminInstructorInput: {
            displayName: string;
            bio: string;
            active: boolean;
            sortOrder: number;
            /**
             * Format: uuid
             * @description Omit to preserve the portrait; null removes it including the bundled preview.
             */
            portraitAssetId?: string | null;
            classes?: components["schemas"]["InstructorClassAssignment"][];
        };
        AdminInstructor: {
            displayName: string;
            bio: string;
            active: boolean;
            sortOrder: number;
            /**
             * Format: uuid
             * @description Omit to preserve the portrait; null removes it including the bundled preview.
             */
            portraitAssetId: string | null;
            classes: components["schemas"]["InstructorClassAssignment"][];
            /** Format: uuid */
            id: string;
            portrait: components["schemas"]["StudioImage"] | null;
        };
        AdminSessionInput: {
            /** Format: uuid */
            classTypeId: string;
            /** Format: uuid */
            instructorId: string;
            /** Format: date-time */
            startAt: string;
            durationMinutes: number;
            arrivalLeadMinutes: number;
            locationName: string;
            locationAddress: string;
            priceCents: number;
            capacity: number;
            equipment: string;
            suitability: string;
        };
        AdminSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            classTypeId: string;
            className: string;
            /** Format: uuid */
            instructorId: string;
            instructorName: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            capacity: number;
            bookingCount: number;
            /** @enum {string} */
            status: "scheduled" | "cancelled" | "completed";
        } & {
            [key: string]: unknown;
        };
        AdminReasonRequest: {
            reason: string;
        };
        AdminAttendanceRequest: {
            /** @enum {string} */
            status: "attended" | "no_show";
            reason: string;
        };
    };
    responses: {
        /** @description Request failed. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SessionId: string;
        BookingId: string;
        ClassTypeId: string;
        ResourceId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAdminStudioStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current studio opening status */
            200: {
                headers: {
                    /** @description no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStudioStatus"];
                };
            };
            /** @description Request failed; registration sync pending (503) keeps booking closed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed; registration sync pending (503) keeps booking closed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStudioStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    open: boolean;
                };
            };
        };
        responses: {
            /** @description Current studio opening status */
            200: {
                headers: {
                    /** @description no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStudioStatus"];
                };
            };
            /** @description Request failed; registration sync pending (503) keeps booking closed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed; registration sync pending (503) keeps booking closed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed; registration sync pending (503) keeps booking closed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request failed; registration sync pending (503) keeps booking closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStudioStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current studio opening status */
            200: {
                headers: {
                    /** @description no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioStatus"];
                };
            };
        };
    };
    getStudioTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        team: components["schemas"]["TeamContent"] | null;
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    adminGetStudioTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeam"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminUpdateStudioTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTeamInput"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeam"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminUploadStudioImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Normalized media asset. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    createInternalApplicationSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Opaque token stored only in an HTTP-only application cookie. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalSessionCreated"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    resolveInternalApplicationSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalSessionTokenRequest"];
            };
        };
        responses: {
            /** @description Current identity or null when the session was revoked or expired. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalSessionResolved"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    revokeInternalApplicationSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalSessionTokenRequest"];
            };
        };
        responses: {
            /** @description Revoked or already absent. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        revoked: true;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    listClassTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active class types in display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ClassType"][];
                    };
                };
            };
        };
    };
    getClassType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active class type and its upcoming sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassTypeDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published reviews with confirmed consent, in display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Review"][];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published news in display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["NewsItem"][];
                    };
                };
            };
        };
    };
    listTransformations: {
        parameters: {
            query?: {
                featured?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published transformations with confirmed consent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Transformation"][];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getPublicMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published WebP image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public schedule without capacity numbers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PublicSession"][];
                        /** @constant */
                        timezone: "Europe/Prague";
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public session detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Studio Balance profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    listMyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent in-account booking and schedule messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AccountNotification"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listMyFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite active class types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["FavoriteClassType"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    addMyFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classTypeId: components["parameters"]["ClassTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    removeMyFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classTypeId: components["parameters"]["ClassTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite removed or already absent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Booking created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
        };
    };
    listMyBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client bookings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Booking"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    previewBookingCancellation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative cancellation mode and fee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationPreview"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelBookingRequest"];
            };
        };
        responses: {
            /** @description Cancelled booking. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational summary with attendance and booking trends. Estimated visit value is not accounting revenue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboard"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminListClassTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Class types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminClassType"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminCreateClassType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminClassTypeInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminUpdateClassType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminClassTypeInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminListInstructors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instructors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminInstructor"][];
                    };
                };
            };
        };
    };
    adminCreateInstructor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminInstructorInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    adminUpdateInstructor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminInstructorInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminListSessions: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminSession"][];
                    };
                };
            };
        };
    };
    adminCreateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSessionInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    adminUpdateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSessionInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminCancelSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminReasonRequest"];
            };
        };
        responses: {
            /** @description Cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminListReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All reviews. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminReview"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminCreateReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminReviewInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminUpdateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminReviewInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminListNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All news. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminNewsItem"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminCreateNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNewsInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    adminUpdateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNewsInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminListTransformations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All transformations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminTransformation"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminCreateTransformation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTransformationInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminUpdateTransformation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTransformationInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMutationResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminUploadTransformationImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Normalized media asset. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    adminGetMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private WebP image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminListBookings: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminRecordAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAttendanceRequest"];
            };
        };
        responses: {
            /** @description Attendance recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
